[tool.poetry]
name = "redantic"
version = "0.1.1"
description = "Simple redis storage for pydantic objects with an interface of the MutableMapping."
authors = ["apollon <Apollon76@yandex.ru>"]
readme = "README.md"
packages = [{include = "redantic"}]

[tool.poetry.dependencies]
python = "^3.10"
pydantic = "^2.12.5"
redis = "^7.1.0"

[tool.poetry.group.dev.dependencies]
mypy = "^1.19.1"
black = "^25.12.0"
flake8 = "^7.3.0"
isort = "^7.0.0"
pytest = "^9.0.2"
types-redis = "^4.6.0"
fakeredis = "^2.33.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
target-version = ['py39', 'py310']
line-length = 120