[tool.poetry]
name = "redantic"
version = "0.1.1"
description = "Simple redis storage for pydantic objects with an interface of the MutableMapping."
authors = ["apollon <Apollon76@yandex.ru>"]
readme = "README.md"
packages = [{include = "redantic"}]

[tool.poetry.dependencies]
python = "^3.12"
pydantic = "^2.10"
redis = "^5.2"


[tool.poetry.group.dev.dependencies]
mypy = "^1.11"
black = "^24.10"
flake8 = "^7.1"
isort = "^5.13"
pytest = "^8.3"
types-redis = "^4.6"
fakeredis = "^2.24"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
target-version = ['py311', 'py312']
line-length = 120